//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.LABURNUM.COM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Fees = new HashSet<Fee>();
            this.Sections = new HashSet<Section>();
            this.Students = new HashSet<Student>();
            this.Students1 = new HashSet<Student>();
        }
    
        public long ClassId { get; set; }
        public string ClassName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual ICollection<Fee> Fees { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Student> Students1 { get; set; }
    }
}
