//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.LABURNUM.COM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaburnumEntities : DbContext
    {
        public LaburnumEntities()
            : base("name=LaburnumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdmissionType> AdmissionTypes { get; set; }
        public DbSet<ApiClient> ApiClients { get; set; }
        public DbSet<Class> Classes { get; set; }
        public DbSet<Fee> Fees { get; set; }
        public DbSet<Salutation> Salutations { get; set; }
        public DbSet<Section> Sections { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentFee> StudentFees { get; set; }
        public DbSet<StudentFeeDetail> StudentFeeDetails { get; set; }
    }
}
